export const GET_TOPICS = 'GET_TOPICS'
export const GET_TOPIC = 'GET_TOPIC'
export const SAVE_SCROLLX = 'SAVE_SCROLLX'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUt = 'USER_LOGOUt'
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR'