export const GET_TOPICS   = 'GET_TOPICS'
export const GET_TOPIC    = 'GET_TOPIC'
export const SAVE_SCROLLY = 'SAVE_SCROLLY'
export const USER_LOGIN   = 'USER_LOGIN'
export const USER_LOGOUT  = 'USER_LOGOUt'
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR'